package config

// Server constants.
const (
	ENV_KEY_PORT = "PORT"
)

// DB constants.
const (
	ENV_KEY_DB_HOST     = "DB_HOST"
	ENV_KEY_DB_PORT     = "DB_PORT"
	ENV_KEY_DB_DATABASE = "DB_DATABASE"
	ENV_KEY_DB_USER     = "DB_USER"
	ENV_KEY_DB_PASSWORD = "DB_PASSWORD"
)

// Header constants.
const (
	HEADER_KEY_X_UID       = "X-Uid"
	HEADER_KEY_X_CLIENT_ID = "X-Client-Id"
)

const (
	ENV_KEY_APP_ENV        = "APP_ENV"
	ENV_KEY_CLIENT_ID      = "CLIENT_ID"
	ENV_KEY_SESSION_COOKIE = "SESSION_COOKIE_NAME"

	// AWS S3
	// ENV_KEY_S3_BUCKET      = "AWS_S3_BUCKET_NAME"
	// ENV_KEY_S3_TEMP_PATH   = "AWS_S3_BUCKET_TEMP_PATH"

	// MinIO (S3 compatible)
	ENV_KEY_MINIO_BUCKET      = "MINIO_BUCKET_NAME"
	ENV_KEY_MINIO_TEMP_PATH   = "MINIO_BUCKET_TEMP_PATH"
	ENV_KEY_MINIO_PUBLIC_PATH = "MINIO_BUCKET_PUBLIC_PATH"
	ENV_KEY_MINIO_ENDPOINT    = "MINIO_ENDPOINT"
	ENV_KEY_MINIO_ACCESS_KEY  = "MINIO_ACCESS_KEY"
	ENV_KEY_MINIO_SECRET_KEY  = "MINIO_SECRET_KEY"
)

type ContextKey uint

const (
	_ ContextKey = iota
	CTX_KEY_USER_ID
	CTX_KEY_USER_ROLE
)

const (
	PRESIGN_URL_EXPIRE_MINUTES = 15
)
